config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'feeds#index'

  resources :feeds, only: [:new, :create, :index, :show] do
    resources :articles, only: [:update], controller: 'feed/articles'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :articles
  has_and_belongs_to_many :users

  # Update local store with any changes to feed / new articles.
  #
  # @return [boolean] true if success, false if failure
  def update_local_storage
    xml = HTTParty.get(self.url).body
    content = Feedjira.parse(xml)

    self.title = Feed.parse_for_title(content)
    self.image = Feed.parse_for_image_source(content)
    self.articles += Feed.convert_articles(content.entries).select do |article|
      is_new = true
      self.articles.each do |existing_article|
        if (existing_article.title == article.title && existing_article.published_date == article.published_date)
          is_new = false
          break
        end
      end
      is_new
    end

    self.save
  end

  # Retrieve current content for feed if not already stored in our system.
  # Returns existing Feed if already known to our system.
  #
  # @param url [string] Feed url to retrieve content for
  # @return [Feed] An instance of our Feed structure
  def self.build_from_url(url)
    feed = Feed.find_by url: url
    if feed.present?
      feed.users.push(User.current) unless feed.users.include?(User.current)
      return feed
    end

    xml = HTTParty.get(url).body
    content = Feedjira.parse(xml)

    feed = Feed.new(url: url)
    feed.users = [User.current]
    feed.title = parse_for_title(content)
    feed.image = parse_for_image_source(content)
    feed.articles = convert_articles(content.entries)

    feed
  end

  private
    def self.convert_articles(entries)
      entries.map do |entry|
        article = Article.new(title: parse_for_title(entry))
        article.url = parse_for_url(entry)
        article.published_date = parse_for_published_date(entry)
        article.description = parse_for_description(entry)

        article
      end
    end

    # Determine and return title for resource.
    #
    # @param resource [Feed/Article] Feed or article to extract title from
    # @return [String] Title of resource
    def self.parse_for_title(resource)
      return resource.title if resource.respond_to?('title') && resource.title.present?
    end

    # Determine and return correct primary url for resource.
    #
    # @param resource [Feed/Article] Feed or article to extract primary url from
    # @return [String] Primary url of resource
    def self.parse_for_url(resource)
      return resource.feed_url if resource.respond_to?('feed_url') && resource.feed_url.present?
      return resource.url if resource.respond_to?('url') && resource.url.present?
    end

    # Determine and return correct image source for resource.
    #
    # @param resource [Feed/Article] Feed or article to extract image source from
    # @return [String] Url of image
    def self.parse_for_image_source(resource)
      return resource.image.url if resource.respond_to?('image') && resource.image.respond_to?('url') && resource.image.url.present?
    end

    # Determine and return description for provided resource.
    #
    # @param resource [Feed/Article] Feed or article to extract description from
    # @return [String] Description of resource
    def self.parse_for_description(resource)
      return resource.description if resource.respond_to?('description') && resource.description.present?
      return resource.summary if resource.respond_to?('summary') && resource.summary.present?
      return resource.content if resource.respond_to?('content') && resource.content.present?
    end

    # Determine and return published date of an article.
    #
    # @param article [Article] Article to extract published date from
    # @return [String] Date article was published
    def self.parse_for_published_date(article)
      return article.published if article.respond_to?('published') && article.published.present?
    end
end

app/controllers/feed/articles_controller.rb
class Feed::ArticlesController < ApplicationController
  def update
    feed_id = params[:feed_id].to_i
    article_id = params[:id].to_i
    read = ActiveModel::Type::Boolean.new.cast(params[:read])

    feed = Feed.find(feed_id)
    article = feed.articles.detect { |article| article.id == article_id }
    article.read = read

    redirect_to feed
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = current_user.feeds
  end

  def show
    sort_by = params['sort_by'].present? ? params['sort_by'] : 'published_date'
    sort_order = params['sort_order'].present? ? params['sort_order'] : 'desc'
    @sort_by = { sort_by.to_sym => sort_order }

    include_read = params['include_read'].present? ? ActiveModel::Type::Boolean.new.cast(params['include_read']) : false

    @feed = current_user.feeds.detect{ |feed| feed.id == params[:id].to_i }
    raise ActiveRecord::RecordNotFound unless @feed.present?

    @articles = @feed.articles.order("#{sort_by} #{sort_order.upcase}")
    @articles = @articles.select { |article| not article.read? } unless include_read
  end

  def new
    @feed = Feed.new(users: [current_user])
  end

  def create
    feed = Feed.build_from_url(params[:feed][:url])
    if feed.save
      redirect_to feed_path(feed.id)
    else
      raise "Failed to add feed: #{params[:feed][:url]}"
    end
  rescue URI::InvalidURIError, NoMethodError, Errno::ECONNREFUSED
    flash[:new_feed_form_error] = 'URL doesn\'t seem to exist. Please try again.'
    redirect_to new_feed_path
  rescue Feedjira::NoParserAvailable
    flash[:new_feed_form_error] = 'URL doesn\'t seem to be an RSS feed. Please try again.'
    redirect_to new_feed_path
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
  # Return the latest published article for a list of articles.
  #
  # @param articles [Array] List of articles
  # @return [Hash] Latest published article
  def latest_published_article(articles)
    articles_temp_store = articles.select { |article| article.published_date.present? }
    articles_temp_store.sort_by{ |article| article.published_date }.last
  end

  # Return the earliest published article for a list of articles.
  #
  # @param articles [Array] List of articles
  # @return [Hash] Latest published article
  def earliest_published_article(articles)
    articles_temp_store = articles.select { |article| article.published_date.present? }
    articles_temp_store.sort_by{ |article| article.published_date }.first
  end

  # Determine if an article contains an image or not.
  #
  # @return [Hash] Article to search
  def article_contains_image?(article)
    /.*<img .*>.*/ === article[:description]
  end

  # Determine if sort item is currently selected.
  #
  # @return [Boolean] True if item is currently selected, false if not
  def selected?(sort_type, sorted_by)
    sort_type.to_s.downcase == sorted_by.keys[0].to_s.downcase
  end

  # Return class for sort item based on if it is currently selected.
  #
  # @param sort_type [String] Name of sort item
  # @param sorted_by [Hash] Single item hash of currently selected sort
  # @return [String] Class to append to sort item
  def selected_class(sort_type, sorted_by)
    selected?(sort_type, sorted_by) ? 'selected' : ''
  end

  # Return next sort order for sort item based on if it is currently selected.
  #
  # @param sort_type [String] Name of sort item
  # @param sorted_by [Hash] Single item hash of currently selected sort
  # @param default [String] Default sort if item is not currently selected
  # @return [String] Sort order to use for next sort of that item
  def sort_order(sort_type, sorted_by, default = 'asc')
    return default if not selected?(sort_type, sorted_by)
    sorted_by.values[0].to_s.downcase == 'asc' ? 'desc' : 'asc'
  end
end

app/views/feeds/_article.html.haml
%li.resource
  .item
    %a.resource-title.no-style{ href: article.url }= article.title
    .tags
      = present_datetime(article.published_date)
  - if article.description.present?
    .resource-description= article.description.html_safe
    .clear

  %p.righty-tighty
    - if article.read?
      %i.fa.fa-circle
      = link_to 'Mark Unread', feed_article_path(feed_id: @feed.id, id: article.id, read: false), method: :put, class: 'gray no-style'
    - else
      %i.fa.fa-circle-o
      = link_to 'Mark Read', feed_article_path(feed_id: @feed.id, id: article.id, read: true), method: :put, class: 'gray no-style'

  .clear

app/views/feeds/_feed.html.haml
%li.resource
  .righty-tighty.tall
    - if feed.image.present?
      = image_tag(feed.image, class: 'rounded-corners resource-image')
    - else
      .no-image

  .righty-tighty.content
    %a.resource-title.no-style{ href: feed_path(feed.id) }= feed.title
    %br
    .resource-description
      %span.bold= feed.articles.count
      %span.metadata= feed.articles.count == 1 ? 'article' : 'articles'
      %br
      %span.bold= feed.articles.select{ |article| article_contains_image?(article) }.count
      %span.metadata= feed.articles.count == 1 ? 'article that contains an image' : 'articles that contain an image'
      %br
      - earliest_published_article = earliest_published_article(feed.articles)
      - if earliest_published_article.present? && earliest_published_article.published_date.present?
        %span.metadata Earliest article was published
        %span.bold= present_datetime(earliest_published_article.published_date)
        %br
      - latest_published_article = latest_published_article(feed.articles)
      - if latest_published_article.present? && latest_published_article.published_date.present?
        %span.metadata Latest article was published
        %span.bold= present_datetime(latest_published_article.published_date)

  .clear

app/views/feeds/_sort.html.haml
-# feed
-# sorted_by = { published_date: 'desc' }

%a.no-style{ class: selected_class('title', sorted_by), |
    href: feed_path(feed[:id], sort_by: 'title', sort_order: sort_order('title', sorted_by)) }
  = fa_icon 'sort', text: 'Title'
|
%a.no-style{ class: selected_class('description', sorted_by), |
    href: feed_path(feed[:id], sort_by: 'description', sort_order: sort_order('description', sorted_by)) }
  = fa_icon 'sort', text: 'Description'
|
%a.no-style{ class: selected_class('published_date', sorted_by), |
    href: feed_path(feed[:id], sort_by: 'published_date', sort_order: sort_order('published_date', sorted_by, 'desc')) }
  = fa_icon 'sort', text: 'Published Date'

app/views/feeds/index.html.haml
.header
  %h1.share-the-road Feeds
  .actions
    %a.text-blue.no-style{ href: new_feed_path }
      = fa_icon 'plus', text: 'Add Feed'

%ul#feeds
  - if @feeds.count <= 0
    .empty-content
      No feeds found for your account.
      %a{ href: new_feed_path } Add
      one and FEED yourself!
  - else
    = render partial: "feed", collection: @feeds

app/views/feeds/new.html.haml
= form_for @feed do |f|
  - if flash[:new_feed_form_error].present?
    .error
      = fa_icon 'exclamation-triangle'
      = flash[:new_feed_form_error]
    %br

  = f.label :url, 'URL'
  %br
  %span.metadata Uniform Resource Locator
  %br
  = f.text_field :url, autofocus: true, required: true
  %br
  = f.submit 'Add Feed'

app/views/feeds/show.html.haml
.header
  %h1.share-the-road
    Articles for
    %span.underline= @feed[:title]
.subheader
  %a.no-style{ href: feeds_path }
    = fa_icon 'chevron-left', text: 'Back to Feeds'
  .actions
    = render partial: 'sort', locals: { feed: @feed, sorted_by: @sort_by }
  .clear

%ul#articles
  - if @articles.present?
    = render partial: "article", collection: @articles
  - else
    %p
      %center
        %h3
          You're all caught up! Have a pleasant day!